apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet-demo-pod-broadcaster
  namespace: intranet-demo
  labels:
    app: intranet-demo-pod-broadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet-demo-pod-broadcaster
  template:
    metadata:
      labels:
        app: intranet-demo-pod-broadcaster
    spec:
      serviceAccountName: pod-broadcaster-serviceaccount
      containers:
        - name: pod-broadcaster
          image: ghcr.io/ministryofjustice/kubernetes-pod-broadcaster:latest
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            runAsUser: 1000
          # Run the 'cluster' task, it passes the cluster cert to deno.
          command: ["/bin/sh", "-c"]
          args: ["deno task cluster"]
          env:
            - name: NAMESPACE
              value: intranet-demo
            - name: LABEL_SELECTOR
              value: app=intranet-demo
            - name: DEBUG
              value: "true"
