apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: intranet-dev-ingress
  namespace: intranet-dev
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: intranet-dev-ingress-intranet-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Development User | Authentication Required'
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'intranet-dev.apps.live.cloud-platform.service.justice.gov.uk') {
        return 301 https://dev.justice.gov.uk;
      }
      location = /health {
        auth_basic off;
        access_log off;
        default_type text/plain;
        add_header Content-Type text/plain;
        return 200 "OK";
      }
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
spec:
  ingressClassName: default
  tls:
  - hosts:
    - intranet-dev.apps.live.cloud-platform.service.justice.gov.uk
  - hosts:
    - dev.justice.gov.uk
    secretName: intranet-dev-cert-secret
  rules:
  - host: intranet-dev.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080
  - host: dev.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080
